### Q_1: create 2D-array that contain even numbers between 0-18...??

In [2]:
import numpy as np
even_numbers = np.arange(0, 20, 2)
array_2d = even_numbers.reshape(2, 5)
print(array_2d)

[[ 0  2  4  6  8]
 [10 12 14 16 18]]


### Q_2: Replace the negative values with 0 in random array that has value in range (-6,6)

In [4]:
random_array = np.random.uniform(-6, 6, size=(3, 4))

print(random_array)

random_array[random_array < 0] = 0

print(random_array)

[[-2.3914686   3.07260277 -0.12559255 -0.86226387]
 [ 1.51235385  5.8336318  -4.6706493  -2.95333916]
 [ 1.63351607  4.57237558  4.69020819 -3.86903331]]
[[0.         3.07260277 0.         0.        ]
 [1.51235385 5.8336318  0.         0.        ]
 [1.63351607 4.57237558 4.69020819 0.        ]]


### Q_3 :  How to compute ((A+B)*(-A/2)) ?  where A,B random array

In [6]:
A = np.random.randint(1, 10, size=(3, 3))  
B = np.random.randint(1, 10, size=(3, 3))

result = (A + B) * (-A / 2)

print("A:")
print(A)

print("\nB:")
print(B)

print("\nResult of ((A + B) * (-A / 2)):")
print(result)

A:
[[6 3 4]
 [4 7 2]
 [7 4 5]]

B:
[[5 7 2]
 [2 7 4]
 [8 3 9]]

Result of ((A + B) * (-A / 2)):
[[-33.  -15.  -12. ]
 [-12.  -49.   -6. ]
 [-52.5 -14.  -35. ]]


### Q_4: How to concatenate two arrays horizontally..?

In [10]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

horizontal_concat = np.hstack((A, B))

print("Horizontal Concatenation:")
print(horizontal_concat)

Horizontal Concatenation:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


#### Q_5: Create a array vector of size 3x3 and sort values in Its columns